version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: memoapp_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: memo_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
